(define (problem hw3)
   (:domain assign3) 
   (:objects arm r1 r2 r3 r4 r5 r6 r7 r8 r9 ball1 ball2 ball3)
   (:init (room r1)
          (room r2) 
          (room r3)
          (room r4)
          (room r5)
          (room r6)
          (room r7)
          (room r8)
          (room r9) 
          (ball ball1)
          (ball ball2)
          (ball ball3)
          (ball-at ball1 r6)
          (ball-at ball2 r4)
          (ball-at ball3 r7) 
          (robot arm)
          (robot-at r1) 
          (linked r1 r4) 
          (linked r2 r3) 
          (linked r3 r6)
          (linked r3 r2)
          (linked r4 r5)
          (linked r4 r1)
          (linked r5 r6)
          (linked r5 r8)
          (linked r5 r4)
          (linked r6 r9) 
          (linked r6 r3)
          (linked r6 r5)
          (linked r7 r8)
          (linked r8 r5)
          (linked r8 r7)
          (linked r9 r6)
	      (empty r1)
          (empty r2)
          (empty r3)
          (empty r5)
          (empty r8)
          (empty r9)
	      (free arm))
   (:goal (and (ball-at ball1 r7) 
               (ball-at ball2 r2)
               (ball-at ball3 r9))))
